/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dexGetDexOverview } from "../funcs/dexGetDexOverview.js";
import { dexGetDexProtocolBySlug } from "../funcs/dexGetDexProtocolBySlug.js";
import { dexGetPoolAnalytics } from "../funcs/dexGetPoolAnalytics.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Dex extends ClientSDK {
  /**
   * Get Solana DEX overview
   *
   * @remarks
   * Returns Solana DEX protocol summaries and aggregated volume timeline for Solana DEXs.
   */
  async getDexOverview(
    options?: RequestOptions,
  ): Promise<operations.GetDexOverviewResponse> {
    return unwrapAsync(dexGetDexOverview(
      this,
      options,
    ));
  }

  /**
   * Get liquidity and volume analytics for a specific Solana pool
   *
   * @remarks
   * Returns time-sensitive liquidity, fee, and reserve metrics for a given Solana pool sourced from the Jupiter Ultra API.
   *
   * Pricing: requires a 0.001 USDC x402 payment on Solana per request.
   */
  async getPoolAnalytics(
    request: operations.GetPoolAnalyticsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPoolAnalyticsResponse> {
    return unwrapAsync(dexGetPoolAnalytics(
      this,
      request,
      options,
    ));
  }

  /**
   * Get DEX protocol details
   *
   * @remarks
   * Returns detailed information about a specific DEX protocol on Solana, including TVL, volume metrics, and protocol metadata.
   */
  async getDexProtocolBySlug(
    request: operations.GetDexProtocolBySlugRequest,
    options?: RequestOptions,
  ): Promise<operations.GetDexProtocolBySlugResponse> {
    return unwrapAsync(dexGetDexProtocolBySlug(
      this,
      request,
      options,
    ));
  }
}
