/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { loggingPostSwapLog } from "../funcs/loggingPostSwapLog.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Logging extends ClientSDK {
  /**
   * Log a swap event
   *
   * @remarks
   * Accepts arbitrary JSON payloads to be logged server-side. Returns no content.
   */
  async postSwapLog(
    request?: { [k: string]: any } | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostSwapLogResponse | undefined> {
    return unwrapAsync(loggingPostSwapLog(
      this,
      request,
      options,
    ));
  }
}
