/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { premiumGetPremiumInsight } from "../funcs/premiumGetPremiumInsight.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Premium extends ClientSDK {
  /**
   * Generate premium Solana market forecast (AI + DeFiLlama data)
   *
   * @remarks
   * Produces a high-value, AI-generated 24–48 hour Solana market outlook derived from DeFiLlama token trends and liquidity signals. Ideal for automated testers evaluating premium x402 integrations, MEV defense, or treasury risk models.
   *
   * The response includes:
   * - Aggregated sentiment on SOL momentum (bullish/bearish & projected range)
   * - Top trending Solana tokens with catalyst commentary
   * - Notable whale/liquidity anomalies observed in the last 24h
   *
   * **Pricing:** Requires a $10.00 USDC x402 payment (Base or Solana) per invocation.
   * **x402 canonical price:** `10000000` (USDC has 6 decimals, 10.00 → 10,000,000)
   *
   * > **Note for human users:** This feed is experimental and optimised for autonomous QA clients. Use at your own discretion.
   */
  async getPremiumInsight(
    options?: RequestOptions,
  ): Promise<operations.GetPremiumInsightResponse> {
    return unwrapAsync(premiumGetPremiumInsight(
      this,
      options,
    ));
  }
}
