/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Dex } from "./dex.js";
import { Logging } from "./logging.js";
import { Premium } from "./premium.js";
import { Stats } from "./stats.js";
import { Trending } from "./trending.js";

export class SundialExchangeApi extends ClientSDK {
  private _dex?: Dex;
  get dex(): Dex {
    return (this._dex ??= new Dex(this._options));
  }

  private _stats?: Stats;
  get stats(): Stats {
    return (this._stats ??= new Stats(this._options));
  }

  private _trending?: Trending;
  get trending(): Trending {
    return (this._trending ??= new Trending(this._options));
  }

  private _logging?: Logging;
  get logging(): Logging {
    return (this._logging ??= new Logging(this._options));
  }

  private _premium?: Premium;
  get premium(): Premium {
    return (this._premium ??= new Premium(this._options));
  }
}
