/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statsGetStats } from "../funcs/statsGetStats.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Stats extends ClientSDK {
  /**
   * Get near real-time platform stats
   *
   * @remarks
   * Returns TPS, SOL price, TVL, and 24h volume plus 24h change percentages when available.
   */
  async getStats(
    options?: RequestOptions,
  ): Promise<operations.GetStatsResponse> {
    return unwrapAsync(statsGetStats(
      this,
      options,
    ));
  }
}
