/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trendingGetTrendingTokens } from "../funcs/trendingGetTrendingTokens.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Trending extends ClientSDK {
  /**
   * Get trending token pricing data
   */
  async getTrendingTokens(
    request: operations.GetTrendingTokensRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTrendingTokensResponse> {
    return unwrapAsync(trendingGetTrendingTokens(
      this,
      request,
      options,
    ));
  }
}
