/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStatsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.StatsResponse;
};

/** @internal */
export const GetStatsResponse$inboundSchema: z.ZodType<
  GetStatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.StatsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type GetStatsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.StatsResponse$Outbound;
};

/** @internal */
export const GetStatsResponse$outboundSchema: z.ZodType<
  GetStatsResponse$Outbound,
  z.ZodTypeDef,
  GetStatsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.StatsResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStatsResponse$ {
  /** @deprecated use `GetStatsResponse$inboundSchema` instead. */
  export const inboundSchema = GetStatsResponse$inboundSchema;
  /** @deprecated use `GetStatsResponse$outboundSchema` instead. */
  export const outboundSchema = GetStatsResponse$outboundSchema;
  /** @deprecated use `GetStatsResponse$Outbound` instead. */
  export type Outbound = GetStatsResponse$Outbound;
}

export function getStatsResponseToJSON(
  getStatsResponse: GetStatsResponse,
): string {
  return JSON.stringify(
    GetStatsResponse$outboundSchema.parse(getStatsResponse),
  );
}

export function getStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStatsResponse' from JSON`,
  );
}
