/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostSwapLogResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const PostSwapLogResponse$inboundSchema: z.ZodType<
  PostSwapLogResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

/** @internal */
export type PostSwapLogResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const PostSwapLogResponse$outboundSchema: z.ZodType<
  PostSwapLogResponse$Outbound,
  z.ZodTypeDef,
  PostSwapLogResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostSwapLogResponse$ {
  /** @deprecated use `PostSwapLogResponse$inboundSchema` instead. */
  export const inboundSchema = PostSwapLogResponse$inboundSchema;
  /** @deprecated use `PostSwapLogResponse$outboundSchema` instead. */
  export const outboundSchema = PostSwapLogResponse$outboundSchema;
  /** @deprecated use `PostSwapLogResponse$Outbound` instead. */
  export type Outbound = PostSwapLogResponse$Outbound;
}

export function postSwapLogResponseToJSON(
  postSwapLogResponse: PostSwapLogResponse,
): string {
  return JSON.stringify(
    PostSwapLogResponse$outboundSchema.parse(postSwapLogResponse),
  );
}

export function postSwapLogResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostSwapLogResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostSwapLogResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostSwapLogResponse' from JSON`,
  );
}
