/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StatsResponse = {
  tps?: number | null | undefined;
  solPriceUsd?: number | null | undefined;
  tvlUsd?: number | null | undefined;
  volume24hUsd?: number | null | undefined;
  solChange24hPct?: number | null | undefined;
  tvlChange24hPct?: number | null | undefined;
  volume24hChangePct?: number | null | undefined;
};

/** @internal */
export const StatsResponse$inboundSchema: z.ZodType<
  StatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  tps: z.nullable(z.number()).optional(),
  solPriceUsd: z.nullable(z.number()).optional(),
  tvlUsd: z.nullable(z.number()).optional(),
  volume24hUsd: z.nullable(z.number()).optional(),
  solChange24hPct: z.nullable(z.number()).optional(),
  tvlChange24hPct: z.nullable(z.number()).optional(),
  volume24hChangePct: z.nullable(z.number()).optional(),
});

/** @internal */
export type StatsResponse$Outbound = {
  tps?: number | null | undefined;
  solPriceUsd?: number | null | undefined;
  tvlUsd?: number | null | undefined;
  volume24hUsd?: number | null | undefined;
  solChange24hPct?: number | null | undefined;
  tvlChange24hPct?: number | null | undefined;
  volume24hChangePct?: number | null | undefined;
};

/** @internal */
export const StatsResponse$outboundSchema: z.ZodType<
  StatsResponse$Outbound,
  z.ZodTypeDef,
  StatsResponse
> = z.object({
  tps: z.nullable(z.number()).optional(),
  solPriceUsd: z.nullable(z.number()).optional(),
  tvlUsd: z.nullable(z.number()).optional(),
  volume24hUsd: z.nullable(z.number()).optional(),
  solChange24hPct: z.nullable(z.number()).optional(),
  tvlChange24hPct: z.nullable(z.number()).optional(),
  volume24hChangePct: z.nullable(z.number()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StatsResponse$ {
  /** @deprecated use `StatsResponse$inboundSchema` instead. */
  export const inboundSchema = StatsResponse$inboundSchema;
  /** @deprecated use `StatsResponse$outboundSchema` instead. */
  export const outboundSchema = StatsResponse$outboundSchema;
  /** @deprecated use `StatsResponse$Outbound` instead. */
  export type Outbound = StatsResponse$Outbound;
}

export function statsResponseToJSON(statsResponse: StatsResponse): string {
  return JSON.stringify(StatsResponse$outboundSchema.parse(statsResponse));
}

export function statsResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatsResponse' from JSON`,
  );
}
